### ISSUE TITLE
What we like about Slack

### ISSUE THREAD

**Issue by JedWatson** [reactiflux/volunteers#23]
In terms of Slack vs. other services / platforms, I thought it would be good to get clear on what is currently good and working about the current Reactiflux Slack.

We can also discuss what isn't great, or things that would be nice to have, but I wanted to focus specifically on understanding what _works_ that should be maintained in any future move we make, in the context that we probably benefit from a specific subset of Slack features.

My current take is:
- The real-time chat experience is second to none, and features like @ mentions, emoticon support, and markdown formatting work really well.
- Private chat is also (I assume) really useful, I know I use it as a preferred way to contact people in the community I want to chat with instead of Skype / email / twitter / etc
- The mix of open channels (#general, etc) and project-specific support (#redux, etc) is great; it puts everyone in the community in the same place, and means projects don't need their own slack / etc. to connect with users
- Notifications (specifically app badges and channel mentions / unread hilighting), cross-platform support (especially native apps) and seamless experience moving between devices w/ unread history makes keeping in touch and up to date easy, especially with more focused channels (I don't think anything could help me keep up with the firehose that is #general)
- A lot of people use Slack at work and have it open all day

The things I am not sure we benefit greatly from are:
- File upload & service support, e.g. Google Docs, although it's useful being able to share screenshots
- How important is email support for notifications?
- User accounts (i.e using GitHub / Facebook / Twitter for auth would be fine)
- Integrations

What does everyone else think?

**Comment by sotojuan** [comment]
Things I like about Slack:
- Easy
- Works well on my phone (IRC apps always seem to be bad/disconnect a lot)

The thing I don't like about Slack is that well, it doesn't seem suited for communities as big as Reactiflux. The chat was always slow for me, and of course Slack will want some money for supporting that many people.

I am always happy to use IRC, but I know it's not convenient for everyone or as easy to use (though a modern client like Textual + a short README on how to join can do wonders) and to mimic Reactiflux we'd need our own server.

Not sure what the other alternatives are.
