### ISSUE TITLE
Reactiflux migration plan

### ISSUE THREAD

**Issue by benigeri** [reactiflux/volunteers#31]
We're almost ready to announce which service we're going to migrate to!
#### Public announcements
- [x] Write blog post (will be published Monday AM)
- [x] Tweet about it
- [x] Update the website
#### Moving people over
- [x] Let's all try and spread the word
- [ ] Tell @everyone in each channel on Slack
- [ ] Write a bot that automatically posts in the different channels

**Comment by ekmartin** [comment]
Should the bot automatically reply in all channels whenever someone posts something? E.g. "Reactiflux has moved to Discord, more information here: ...".

**Comment by jhgg** [comment]
Grammar on the website is wrong:

> They've want to work with the Reactiflux community to make sure it's the best home for us, and already host communities larger than ours.

Should be:

> They want to work with the Reactiflux community to make sure it's the best home for us and already host communities larger than ours.

**Comment by taion** [comment]
I think we should archive the channels on the Reactiflux Slack as we go.

**Comment by onewheelskyward** [comment]
How about "In addition to hosting larger communities than Reactiflux, Discord is eager to work with us to ensure it's a good fit."  The sentence as it (still) exists on the site is a bit awkward.

**Comment by taion** [comment]
Can we close this out?
