### ISSUE TITLE
Wanna join as a volunteers but link not working :(

### ISSUE THREAD

**Issue by rajasekarm** [reactiflux/volunteers#33]
https://discord.gg/0ZcbPKXt5bYZVCkR

**Comment by ekmartin** [comment]
That's an invite link to the Reactiflux [Discord](https://discordapp.com/), which is the chat service we're using. It seems to be working fine for me though, so not completely sure what you're referring to here.

Information about joining as a volunteer is available in the README, [here](https://github.com/reactiflux/volunteers#the-troops).
