### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by js08** [reactiflux/volunteers#34]
https://github.com/facebook/react/issues/6010

**Comment by taion** [comment]
I just checked – the link still works for me, and that instant invite code still shows up on the list. Try again.

**Comment by js08** [comment]
can you send me the link...I might use the wrong URL

**Comment by taion** [comment]
https://discordapp.com/invite/0ZcbPKXt5bZiQhB5

**Comment by js08** [comment]
@taion it shows expired :(

**Comment by benigeri** [comment]
yeah super weird, link looks good for me. Will ping discord people.

**Comment by js08** [comment]
OK thanks

**Comment by benigeri** [comment]
@js08 can you try in incognito? Then clear your cookies and try again? If you have already tried that let me know. This is unusual.

**Comment by js08** [comment]
@benigeri in another browser its working but after that if i logout how to get back to react channel

**Comment by js08** [comment]
@benigeri neede help :(

**Comment by benigeri** [comment]
@js08 we need more information to debug what's going on please give us details on how to reproduce. 
- Have you tried clearing you cache and cookies? 
- What browser are you using? 
- Does it work in incognito? 
- What IP address are you using?

**Comment by taion** [comment]
I banned you for spamming. I've lifted your ban for the time being. If I see you cross-posting questions onto multiple unrelated channels again, I will not lift your ban a second time.

**Comment by taion** [comment]
I take that back: http://pipend.github.io/reactiflux-dashboard/#/?ago=custom&from=2016-02-11T00%3A00&to=2016-02-11T23%3A59&username=js08

Your ban has been reinstated. Enjoy.

**Comment by taion** [comment]
For full reference, this was what drove the initial ban: http://pipend.github.io/reactiflux-dashboard/#/?ago=custom&from=2016-01-30T00%3A00&to=2016-01-30T23%3A59&username=js08.

**Comment by benigeri** [comment]
lol good call here @taion
